/**
 * Email Sender using Resend
 * Sends the weekly payment report via email with PDF attachment
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const REPORT_RECIPIENTS = process.env.REPORT_RECIPIENTS;

/**
 * Send the weekly report email using Resend API
 * @param {string} pdfPath - Path to the PDF report file
 * @param {string} htmlPath - Path to the HTML report file (optional)
 * @param {Object} summary - Report summary data
 */
async function sendReportEmail(pdfPath, htmlPath, summary = {}) {
    if (!RESEND_API_KEY) {
        throw new Error('Missing Resend API key. Set RESEND_API_KEY environment variable.');
    }

    if (!REPORT_RECIPIENTS) {
        throw new Error('No recipients configured. Set REPORT_RECIPIENTS environment variable.');
    }

    const recipients = REPORT_RECIPIENTS.split(',').map(email => email.trim());

    // Format date range for subject
    const startDate = summary.startDate || 'Unknown';
    const endDate = summary.endDate || 'Unknown';
    const today = new Date().toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric'
    });

    const subject = `DLC Weekly Report - ${startDate} to ${endDate}`;

    // Build HTML body with summary
    const htmlBody = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0; }
        .content { background: #f8f9fa; padding: 20px; border-radius: 0 0 8px 8px; }
        .summary-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 20px 0; }
        .summary-card { background: white; padding: 15px; border-radius: 5px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .summary-card.success { border-left: 4px solid #11998e; }
        .summary-card.error { border-left: 4px solid #eb3349; }
        .summary-card.apps { border-left: 4px solid #667eea; }
        .metric { font-size: 24px; font-weight: bold; color: #333; }
        .label { font-size: 12px; color: #666; text-transform: uppercase; }
        .footer { margin-top: 20px; font-size: 12px; color: #888; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1 style="margin: 0; font-size: 24px;">Weekly Application & Payment Report</h1>
            <p style="margin: 10px 0 0 0; opacity: 0.9;">${startDate} to ${endDate}</p>
        </div>
        <div class="content">
            <p>Hi team,</p>
            <p>Please find attached the weekly application and payment report for the Dollar Loan Center.</p>

            ${summary.applications ? `
            <div class="summary-grid">
                <div class="summary-card apps">
                    <div class="label">Total Applications</div>
                    <div class="metric">${summary.applications.total?.toLocaleString() || 'N/A'}</div>
                </div>
                <div class="summary-card apps">
                    <div class="label">First Time Apps</div>
                    <div class="metric">${summary.applications.firstTime?.toLocaleString() || 'N/A'}</div>
                </div>
            </div>
            ` : ''}

            ${summary.payments ? `
            <div class="summary-grid">
                <div class="summary-card success">
                    <div class="label">Payment Success</div>
                    <div class="metric">${summary.payments.successEvents?.toLocaleString() || 'N/A'}</div>
                    <div style="font-size: 12px; color: #666;">${summary.payments.successUsers?.toLocaleString() || 'N/A'} users</div>
                </div>
                <div class="summary-card error">
                    <div class="label">Payment Errors</div>
                    <div class="metric">${summary.payments.errorEvents?.toLocaleString() || 'N/A'}</div>
                    <div style="font-size: 12px; color: #666;">${summary.payments.errorUsers?.toLocaleString() || 'N/A'} users</div>
                </div>
            </div>
            ` : ''}

            <p>The full detailed report is attached as a PDF.</p>

            <div class="footer">
                <p>This is an automated email generated by the DLC Sentry API Report system.</p>
                <p>Generated on ${today}</p>
            </div>
        </div>
    </div>
</body>
</html>
    `;

    // Build attachments array
    const attachments = [];

    if (pdfPath && fs.existsSync(pdfPath)) {
        const pdfContent = fs.readFileSync(pdfPath);
        attachments.push({
            filename: path.basename(pdfPath),
            content: pdfContent.toString('base64')
        });
    }

    if (attachments.length === 0) {
        throw new Error('No report files found to attach');
    }

    console.log(`\nSending email via Resend...`);
    console.log(`To: ${recipients.join(', ')}`);
    console.log(`Subject: ${subject}`);
    console.log(`Attachments: ${attachments.map(a => a.filename).join(', ')}`);

    // Send via Resend API
    const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${RESEND_API_KEY}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            from: 'DLC Weekly Report <onboarding@resend.dev>',
            to: recipients,
            subject: subject,
            html: htmlBody,
            attachments: attachments
        })
    });

    const result = await response.json();

    if (!response.ok) {
        throw new Error(`Resend API error: ${result.message || JSON.stringify(result)}`);
    }

    console.log(`✓ Email sent successfully! ID: ${result.id}`);
    return result;
}

// Export for use in other modules
module.exports = { sendReportEmail };

// Allow running directly for testing
if (require.main === module) {
    const args = process.argv.slice(2);

    if (args.length < 1) {
        console.log('Usage: node send_email.js <pdf-path>');
        console.log('Example: node send_email.js ./data/processed/payment_report_2026-01-20.pdf');
        process.exit(1);
    }

    const pdfPath = args[0];

    sendReportEmail(pdfPath, null, {
        startDate: '2026-01-13',
        endDate: '2026-01-20',
        applications: { total: 1468, firstTime: 640 },
        payments: { successEvents: 5512, successUsers: 5326, errorEvents: 883, errorUsers: 791 }
    })
        .then(() => console.log('\nDone!'))
        .catch(error => {
            console.error('Error:', error.message);
            process.exit(1);
        });
}
